name: video_player_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # file_selector: ^1.0.4
  file_picker: ^10.3.3
  image_picker: ^1.2.0

  sensors_plus: ^7.0.0

  fvp: ^0.34.0
  chewie: ^1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true